-- ==========================================
-- Ayurelix Real-World E-Commerce Schema Setup
-- ==========================================

-- 1. Create Profiles Table (Linked to Supabase Auth)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  email text,
  phone text,
  address text,
  city text,
  state text,
  postal_code text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on Profiles
alter table public.profiles enable row level security;

-- Alter profiles table to add missing columns if they don't exist
alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists address text;
alter table public.profiles add column if not exists city text;
alter table public.profiles add column if not exists state text;
alter table public.profiles add column if not exists postal_code text;

-- Drop existing policies first to prevent conflicts
drop policy if exists "Users can view their own profile" on public.profiles;
drop policy if exists "Users can update their own profile" on public.profiles;

-- Profiles Policies
create policy "Users can view their own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update their own profile" on public.profiles
  for update using (auth.uid() = id);

-- Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    new.email
  )
  on conflict (id) do nothing;
  return new;
exception
  when others then
    return new;
end;
$$ language plpgsql security definer set search_path = public;

-- Recreate trigger (drop first to prevent duplicate errors)
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. Create Products Table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  description text,
  category text,
  stock integer default 100,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Alter table to add image_url column if it doesn't exist for existing databases
alter table public.products add column if not exists image_url text;

-- Enable RLS on Products
alter table public.products enable row level security;

-- Drop existing policies first to prevent conflicts
drop policy if exists "Allow public read access to products" on public.products;
drop policy if exists "Allow admin write access to products" on public.products;

-- Products Policies
create policy "Allow public read access to products" on public.products
  for select using (true);

create policy "Allow admin write access to products" on public.products
  for all using (auth.jwt()->>'email' = 'admin@ayurelix.com');

-- Insert Default Products if they don't exist
insert into public.products (id, name, price, description, category, stock, image_url)
values 
  (1, 'Kumkumadi Oil', 799, 'Premium Kumkumadi Oil (15ml) for anti-aging, glow, and smooth skin. Crafted with traditional Ayurvedic oils and saffron.', '1', 100, '/src/assets/kumkumadi_serum.jpg'),
  (2, 'Anti Pigmentation Cream', 499, 'Natural Anti Pigmentation Cream (50gm) for reducing dark spots, blemishes, and acne scars. Intensively brightens skin.', '2', 100, '/src/assets/anti_pigmentation.jpg')
on conflict (id) do update set
  name = excluded.name,
  price = excluded.price,
  description = excluded.description,
  category = excluded.category,
  image_url = excluded.image_url;

-- Remove other products to ensure only these two are present
delete from public.products where id not in (1, 2);


-- 3. Create Orders Table
create table if not exists public.orders (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  total_amount numeric not null,
  status text default 'paid'::text not null, -- 'paid', 'shipped', 'delivered'
  payment_id text,
  shipping_address jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on Orders
alter table public.orders enable row level security;

-- Drop existing policies first to prevent conflicts
drop policy if exists "Users can view their own orders" on public.orders;
drop policy if exists "Users can create their own orders" on public.orders;
drop policy if exists "Admins can manage all orders" on public.orders;

-- Orders Policies
create policy "Users can view their own orders" on public.orders
  for select using (auth.uid() = user_id);

create policy "Users can create their own orders" on public.orders
  for insert with check (auth.uid() = user_id);

create policy "Admins can manage all orders" on public.orders
  for all using (auth.jwt()->>'email' = 'admin@ayurelix.com');


-- 4. Create Order Items Table
create table if not exists public.order_items (
  id uuid default gen_random_uuid() primary key,
  order_id uuid references public.orders on delete cascade not null,
  product_id bigint references public.products on delete cascade not null,
  quantity integer not null,
  price numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on Order Items
alter table public.order_items enable row level security;

-- Drop existing policies first to prevent conflicts
drop policy if exists "Users can view their own order items" on public.order_items;
drop policy if exists "Users can insert their own order items" on public.order_items;
drop policy if exists "Admins can manage all order items" on public.order_items;

-- Order Items Policies
create policy "Users can view their own order items" on public.order_items
  for select using (
    exists (
      select 1 from public.orders 
      where public.orders.id = public.order_items.order_id 
      and public.orders.user_id = auth.uid()
    )
  );

create policy "Users can insert their own order items" on public.order_items
  for insert with check (
    exists (
      select 1 from public.orders 
      where public.orders.id = public.order_items.order_id 
      and public.orders.user_id = auth.uid()
    )
  );

create policy "Admins can manage all order items" on public.order_items
  for all using (auth.jwt()->>'email' = 'admin@ayurelix.com');


-- 5. Create Reviews Table
create table if not exists public.reviews (
  id uuid default gen_random_uuid() primary key,
  product_id bigint references public.products on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  rating integer check (rating >= 1 and rating <= 5) not null,
  comment text,
  user_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on Reviews
alter table public.reviews enable row level security;

-- Drop existing policies first to prevent conflicts
drop policy if exists "Allow public read access to reviews" on public.reviews;
drop policy if exists "Allow public read access to reviews" on reviews;
drop policy if exists "Users can create their own reviews" on public.reviews;
drop policy if exists "Users can create their own reviews" on reviews;
drop policy if exists "Users can delete their own reviews" on public.reviews;
drop policy if exists "Users can delete their own reviews" on reviews;
drop policy if exists "Admins can manage all reviews" on public.reviews;
drop policy if exists "Admins can manage all reviews" on reviews;

-- Reviews Policies
create policy "Allow public read access to reviews" on public.reviews
  for select using (true);

create policy "Users can create their own reviews" on public.reviews
  for insert with check (auth.uid() = user_id);

create policy "Users can delete their own reviews" on public.reviews
  for delete using (auth.uid() = user_id);

create policy "Admins can manage all reviews" on public.reviews
  for all using (auth.jwt()->>'email' = 'admin@ayurelix.com');


-- ==========================================
-- 6. Create Categories Table
-- ==========================================
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  subtitle text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on categories
alter table public.categories enable row level security;

-- Categories Policies
drop policy if exists "Allow public read access to categories" on public.categories;
drop policy if exists "Allow admin write access to categories" on public.categories;

create policy "Allow public read access to categories" on public.categories
  for select using (true);

create policy "Allow admin write access to categories" on public.categories
  for all using (auth.jwt()->>'email' = 'admin@ayurelix.com');

-- 7. Add columns to Products Table
alter table public.products add column if not exists is_bestseller boolean default false;
alter table public.products add column if not exists category_id bigint references public.categories(id) on delete set null;

-- 8. Insert Default Categories
insert into public.categories (id, name, subtitle, image_url)
values
  (1, 'Skincare', 'Premium Ayurvedic Skincare', ''),
  (2, 'Face Care', 'Natural Face Care Solutions', ''),
  (3, 'Hair Care', 'Healthy Hair Essentials', ''),
  (4, 'Eye Care', 'Ayurvedic Eye Wellness', ''),
  (5, 'Hair & Skin Care', 'Complete Beauty Care', ''),
  (6, 'Body Care', 'Herbal Body Care Collection', ''),
  (7, 'Wellness Care', 'Traditional Wellness Products', ''),
  (8, 'Ayurvedic Essentials', 'Daily Ayurvedic Essentials', '')
on conflict (id) do update set
  name = excluded.name,
  subtitle = excluded.subtitle;

-- 9. Clean up and link default products
update public.products set category_id = 1, is_bestseller = true where id = 1;
update public.products set category_id = 2, is_bestseller = true where id = 2;


-- 10. Stock and Inventory Policies/Triggers
-- A. Update policy to allow authenticated users to update products (specifically for stock decrement client-side fallback)
drop policy if exists "Allow authenticated users to update product stock" on public.products;
create policy "Allow authenticated users to update product stock" on public.products
  for update using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- B. Automate stock decrement using database trigger (Recommended, running as security definer)
create or replace function public.decrement_product_stock()
returns trigger as $$
begin
  update public.products
  set stock = greatest(0, stock - new.quantity)
  where id = new.product_id;
  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists tr_decrement_product_stock on public.order_items;
create trigger tr_decrement_product_stock
  after insert on public.order_items
  for each row execute procedure public.decrement_product_stock();


